# RESSPECT
Based on ReadTheDocs : https://resspect.readthedocs.io/en/latest/index.html

In [1]:
!python --version

Python 3.8.5

In [2]:
import os
from resspect.fit_lightcurves import LightCurve
import pandas as pd
import numpy as np
np.random.seed(42)
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [3]:
import sys
import warnings

if not sys.warnoptions:
    warnings.simplefilter("ignore")

In [4]:
path_to_metadata = '/home/sidchaini/resspect_work/plasticc_workdir/data/plasticc_test_metadata.csv'
path_to_lightcurves = '/home/sidchaini/resspect_work/plasticc_workdir/data/plasticc_test_set_batch1.csv'

# path_to_metadata = '/home/sidchaini/resspect_work/plasticc_workdir/data/plasticc_train_metadata.csv'
# path_to_lightcurves = '/home/sidchaini/resspect_work/plasticc_workdir/data/plasticc_train_lightcurves.csv'

In [5]:
df = pd.read_csv(path_to_lightcurves)

In [6]:
object_ids = np.unique(df["object_id"].values)

In [7]:
del(df)

In [8]:
metadata = pd.read_csv(path_to_metadata)

In [9]:
metadata = metadata.set_index("object_id")

In [10]:
metadata = metadata.loc[object_ids]

In [11]:
metadata = metadata[metadata["ddf_bool"] == 1]

In [12]:
metadata = metadata[metadata["true_z"]>0]

In [13]:
metadata["true_target"].value_counts()

42     15986
90     12640
62      2194
52       807
88       363
67       362
993      142
95        98
15        68
992       31
994        6
64         2
Name: true_target, dtype: int64

In [14]:
metadata

,ra,decl,ddf_bool,hostgal_specz,hostgal_photoz,hostgal_photoz_err,distmod,mwebv,target,true_target,...,true_rv,true_av,true_peakmjd,libid_cadence,tflux_u,tflux_g,tflux_r,tflux_i,tflux_z,tflux_y
object_id,,,,,,,,,,,,,,,,,,,,,
13,34.4531,-5.2295,1,0.305,0.319,0.054,41.112,0.019,0,42,...,0.0,0.0,60499.461,124,0.0,0.0,0.0,0.0,0.0,0.0
14,33.3984,-4.3311,1,-9.000,0.632,0.018,42.877,0.018,0,42,...,0.0,0.0,59792.121,120,0.0,0.0,0.0,0.0,0.0,0.0
17,348.5294,-61.7554,1,-9.000,0.830,0.060,43.600,0.016,0,42,...,0.0,0.0,60543.566,85,0.0,0.0,0.0,0.0,0.0,0.0
23,34.8047,-5.8292,1,-9.000,0.653,0.148,42.964,0.023,0,90,...,0.0,0.0,60137.480,97,0.0,0.0,0.0,0.0,0.0,0.0
34,351.3214,-64.1987,1,0.456,0.462,0.012,42.054,0.023,0,90,...,0.0,0.0,60245.078,68,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342818,1.7234,-45.9811,1,0.322,0.325,0.010,41.159,0.010,0,67,...,0.0,0.0,60171.184,114,0.0,0.0,0.0,0.0,0.0,0.0
342825,52.9102,-27.9532,1,0.425,0.382,1.234,41.570,0.007,0,42,...,0.0,0.0,60513.152,52,0.0,0.0,0.0,0.0,0.0,0.0
342834,53.9648,-28.6310,1,-9.000,0.771,0.083,43.403,0.009,0,90,...,0.0,0.0,59885.824,121,0.0,0.0,0.0,0.0,0.0,0.0
342860,150.9961,4.1815,1,0.640,0.623,0.022,42.839,0.015,0,42,...,0.0,0.0,60351.688,12,0.0,0.0,0.0,0.0,0.0,0.0
342868,151.5234,3.1349,1,-9.000,0.457,0.734,42.028,0.019,0,42,...,0.0,0.0,60401.902,125,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:

obj_class = {
    90: "SNIa", # WD detonation, Type Ia SN
    67: "SNIa-91bg", # Peculiar type Ia: 91bg
    52: "SNIax", # Peculiar SNIax
    42: "SNII", # Core Collapse, Type II SN
    62: "SNIbc", # Core Collapse, Type Ibc SN
    95: "SLSN-I", # Super-Lum. SN (magnetar)
    15: "TDE", # Tidal Disruption Event
#     64: "KN", # Kilonova (NS-NS merger)
    88: "AGN", # Active Galactic Nuclei
#     92: "RRL", # RR lyrae
#     65: "M-dwarf", # M-dwarf stellar flare
#     16: "EB", # Eclipsing Binary stars
#     53: "Mira", # Pulsating variable stars
#      6: "µLens-Single" # µ-lens from cosmic strings
}

In [16]:
ls=[]
for aclass in obj_class.keys():
    ls = ls + list(metadata[metadata["true_target"]==aclass].sample(n=60).index)

ls = np.array(ls)

In [17]:
metadata = metadata.loc[ls]

In [18]:
metadata["true_target"].value_counts()

15    60
42    60
52    60
62    60
67    60
88    60
90    60
95    60
Name: true_target, dtype: int64

In [19]:
metadata = metadata.reset_index()

In [20]:
metadata

,object_id,ra,decl,ddf_bool,hostgal_specz,hostgal_photoz,hostgal_photoz_err,distmod,mwebv,target,...,true_rv,true_av,true_peakmjd,libid_cadence,tflux_u,tflux_g,tflux_r,tflux_i,tflux_z,tflux_y
0,314105,53.6133,-27.9532,1,-9.000,1.176,0.044,44.535,0.007,0,...,0.0,0.0,60240.195,56,0.0,0.0,0.0,0.0,0.0,0.0
1,37718,150.1172,2.2387,1,-9.000,0.870,0.039,43.728,0.016,0,...,0.0,0.0,60446.961,26,0.0,0.0,0.0,0.0,0.0,0.0
2,248248,53.9648,-28.6310,1,-9.000,0.909,0.093,43.844,0.009,0,...,0.0,0.0,60235.059,121,0.0,0.0,0.0,0.0,0.0,0.0
3,237722,0.5895,-47.1613,1,0.613,0.614,0.008,42.799,0.009,0,...,0.0,0.0,60126.590,10,0.0,0.0,0.0,0.0,0.0,0.0
4,133914,349.0461,-61.9438,1,0.351,0.322,0.038,41.131,0.017,0,...,0.0,0.0,59830.164,69,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,235595,347.8125,-63.4483,1,0.277,0.268,0.960,40.673,0.021,0,...,0.0,0.0,59570.000,92,19.4,17.4,20.0,22.1,33.5,30.2
476,111076,151.1719,2.5374,1,-9.000,0.923,0.013,43.885,0.024,0,...,0.0,0.0,59570.000,29,18.7,22.9,25.7,25.3,29.6,35.6
477,175848,150.2930,2.6867,1,-9.000,0.242,0.008,40.427,0.016,0,...,0.0,0.0,59570.000,59,3.8,4.1,5.7,8.3,10.5,11.6
478,266706,359.4467,-44.2015,1,-9.000,1.306,0.095,44.817,0.010,0,...,0.0,0.0,59570.000,13,9.0,10.1,13.4,14.7,15.2,15.0
479,94074,1.7532,-46.7685,1,0.498,0.568,0.032,42.596,0.014,0,...,0.0,0.0,59570.000,22,8.3,10.5,11.2,14.9,16.7,27.0

In [21]:
df = pd.read_csv(path_to_lightcurves)

In [22]:
df = df.loc[df['object_id'].isin(metadata["object_id"].values)].reset_index(drop=True)

In [23]:
# df.to_csv("/home/sidchaini/resspect_work/plasticc_workdir/data/plasticc_test_set_batch1_subset.csv",index=False)
# del(df)

In [24]:
allclasses = metadata["true_target"].replace(obj_class)

In [25]:
df["passband"].value_counts()

0    29640
1    25855
2    25855
3    25855
4    25778
5    25555
Name: passband, dtype: int64

In [26]:
banddict = {
    0:"u",
    1:"g",
    2:"r",
    3:"i",
    4:"z",
    5:"Y"
}

In [27]:
df.columns = ['object_id', 'mjd', 'band', 'flux', 'fluxerr', 'detected_bool']
df["band"] = df["band"].replace(banddict)

In [28]:
if not os.path.isdir("csv_data/"):
    os.mkdir("csv_data/")

In [29]:
from tqdm.notebook import tqdm

for i in tqdm(range(len(metadata))):
    snid = metadata['object_id'].iloc[i]
    classname = allclasses.values[i]
    df_sub = df[df["object_id"] == snid][['mjd', 'band', 'flux', 'fluxerr', 'detected_bool']]
    df_sub.to_csv(f"csv_data/{snid}_{classname}.csv",index=False)

  0%|          | 0/480 [00:00<?, ?it/s]